name: "Create GitHub Release"
on:
  push:
    tags:
      - "v*" # vで始まるタグがプッシュされた時に実行

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: "pnpm"

      # バージョン情報と日付を取得
      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Get current date
        id: date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # 拡張機能をビルドしパッケージング
      - name: Build the extension
        run: pnpm build
      - name: Package the extension into a zip artifact
        run: pnpm package

      # GitHubリリースを作成
      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: v${{ steps.get_version.outputs.VERSION }}-${{ steps.date.outputs.DATE }}
          tag_name: ${{ github.ref }}
          files: |
            build/chrome-mv3-prod.zip
          draft: false
          prerelease: false
          generate_release_notes: true
